id: colbertNeg_base
title: "Training Cross encoders with Colbert Negatives"
description:
    Compare three losses using the same sampling of ColBert Negatives

parent: ../core_base # load configuration from core base.

seed: 12 # To mimick the HF xp
nb_repetitions: 3

### Overrides parameters from core_base
learner:
    fabric:
        precision: bf16-mixed

retrieval:
    requirements: duration=20h & cpu(cores=20) & cuda(mem=30G) * 2
    batch_size: 64
    k: 1000

evaluation:
    all_datasets: false
    in_domain: true
    beir13: true
    robust04: true
    lotte_search: true
    # nanobeir: true

# max_len deberta is 512
max_length: 1024
normalize_docs_per_batch: true

#### Params that are grid searched
grid_search:
    base:
        values_list:
            - microsoft/deberta-v3-base
            - jhu-clsp/ettin-encoder-150m

    learner.loss:
        values_list:
            - infoNCE_Colbertv2Neg
            - infoNCE_RankDistiLLM
            - distillRankNET
            - ADR_MSE
