[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cross-encoders"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "experimaestro-ir[anserini,neural]",
    "experimaestro>=2.1.0",
    "datamaestro-ir",
    "ir-datasets",
    "pandas>=3.0.0",
    "tabulate>=0.9.0",
    "transformers>=5.0.0",
    "xpm-torch",
    "torch",
    "accelerate>=1.13.0",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.mypy]
plugins = ["experimaestro.mypy"]


# Our cluster don't have Cuda 13 yet
[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu126", marker = "sys_platform != 'darwin'" }
experimaestro = { path = "experimaestro-python", editable = true }
experimaestro-ir = { path = "experimaestro-ir", editable = true }
datamaestro-ir = { path = "datamaestro-ir", editable = true }
ir-datasets = { git = "https://github.com/bpiwowar/ir_datasets.git" }

[dependency-groups]
dev = [
    "matplotlib>=3.10.8",
    "notebook>=7.5.4",
    "pre-commit>=4.5.1",
    "pytest>=9.0.2",
]
