id: cross_scorer_evaluation
title: cross_scorer_evaluation
description: Experiment whose purpose is to evaluate HF Cross-scorers

module: HF_eval.baselines
pre_experiment: ../pre_experiment.py

gpu: true

scorers_hf_id:
  # - cross-encoder/ms-marco-MiniLM-L12-v2
  - tomaarsen/ms-marco-ettin-150m-reranker
  # - xpmir/cross-encoder-MiniLM-L12-MarginMSE
  # - cross-encoder/ms-marco-MiniLM-L6-v2
  # - tomaarsen/ms-marco-ettin-68m-reranker
  # - tomaarsen/ms-marco-ettin-32m-reranker
  # - tomaarsen/ms-marco-ettin-17m-reranker

retrievers_hf_id:
  - naver/splade-v3-distilbert

indexation:
  requirements: duration=8h & cpu(cores=4, mem=10G) & cuda(mem=10G)
  sparse2bmp_requirements: duration=8h & cpu(cores=8)
  batch_size: 128

retrieval:
  requirements: duration=10h & cpu(cores=4, mem=10G) & cuda(mem=10G)
  batch_size: 512
  k: 1000

evaluation:
  #just for debugging
  test_max_topics: 100
  in_domain_only: true
