id: cross_scorer_evaluation
title: cross_scorer_evaluation
description: Experiment whose purpose is to evaluate HF Cross-scorers

## pre_experiment: pre_experiment
module: HF_eval.baselines

gpu: true


retrievers_hf_id:
  - naver/splade-v3-distilbert

retrievers_only: true

indexation:
    requirements: duration=8h & cpu(cores=5) & cuda(mem=24G)
    sparse2bmp_requirements: duration=8h & cpu(cores=8)

retrieval:
  requirements: duration=20h & cpu(cores=16) & cuda(mem=30G)
  batch_size: 128
  k: 1000

#just for debugging
evaluation:
  all_datasets: false
