id: core_base_ettin
parent: core_base # load configuration from core base.
title: "Validation comparison experiment"
description:
    we remove the infoNCE_rankdistill and use h100 for remaining fever evals..

seed: 12 # To mimick the HF xp
nb_repetitions: 1


### Overrides parameters from core_base
learner:
    optimization:
        batch_size: 8 #with infoNCE = 64docs per batch (1 pos)

max_doc_len: 1024

normalize_docs_per_batch: false

retrieval:
    requirements: duration=20h & cpu(cores=16) & cuda(mem=30G)
    k: 100

evaluation:
    all_datasets: false
    in_domain_only: true

#### Params that are grid searched
grid_search:
    base:
        values_list:
            - jhu-clsp/ettin-encoder-150m
    learner.loss:
        values_list:
            - infoNCE_RankDistiLLM
