id: ir_training_debug
title: "Debugging main Cross Encoder training Experiment"
description: 
    Starts from the checkpoint > microsoft/MiniLM-L12-H384-uncased
    trains on MS_Marco with margin MSE loss, distilling from Hofstätter et al. 2020

module: src.ir_training.experiment

gpu: true
seed: 12 # To mimick the HF xp 
nb_repetitions: 1

retriever: "" #BM25 by default

#model definition
base: microsoft/MiniLM-L12-H384-uncased
#Can be microsoft/MiniLM-L12-H384-uncased, jhu-clsp/ettin-encoder-32m , bert-base-uncased 

attn_patches: #debug setup, mid fusion 
    -   mask_attention_from : 
            - "query"
        mask_attention_to : 
            - "document"
            - "sep_1"
        start_layer : 0
        end_layer : 9
    -   mask_attention_from : 
            - "document"
        mask_attention_to : 
            - "query"
            - "cls"
            - "sep_2"
        start_layer : 0
        end_layer : 8


preprocessing:
    requirements: duration=8h & cpu(cores=8)

indexation:
    requirements: duration=8h & cpu(cores=5)

validation:
    # Use 500 topics for validation
    size: 500

# This set of hyperparameters follows: https://github.com/huggingface/sentence-transformers/blob/9f76b5790fa8f0175ccdc27e41f9ae348f557144/examples/training/ms_marco/train_cross-encoder-v2.py
learner:
    optimization:
        steps_per_epoch: 100
        batch_size: 64
        max_epochs: 10 # Just for debugging
        num_warmup_steps: 5000 # Follows the original setup
        weight_decay: 0.00
        lr: 7e-6
        eps: 1.0e-8
    # sample_max: 2_000_000
    max_grad_norm: 1.0
    checkpoint_interval: 100
    validation_interval: 5
    validation_top_k: 100
    requirements: duration=2 days & cpu(cores=5) & cuda(mem=30G)

    # precision: "bf16" # to test fabric management of precision

retrieval:
    requirements: duration=20h & cpu(cores=16) & cuda(mem=30G)
    k: 1000

#just for debugging
evaluation:
    test_max_topics: 100
    all_datasets: false