id: colbertNeg_infoNCE_precision
title: "Training Cross encoders with Colbert Negatives"
description:
    Study the impact of float precision for training MiniLM

parent: ../core_mini # load configuration from core base.

nb_repetitions: 3

### Overrides parameters from core_base


retrieval:
    requirements: duration=20h & cpu(cores=16) & cuda(mem=30G) * 2
    batch_size: 64
    k: 1000

evaluation:
    all_datasets: false
    in_domain: true
    beir13: true
    robust04: true
    lotte_search: true
    # nanobeir: true

# max_len bert is 512
max_length: 1024
normalize_docs_per_batch: true

#### Params that are grid searched
grid_search:
    base:
        values_list:
            - microsoft/MiniLM-L12-H384-uncased

    learner.fabric.precision:
        values_list:
            - bf16-mixed
            - 32-true #default use by Fabric

    learner.loss:
        values_list:
            - infoNCE_RankDistiLLM
