id: core_base_deberta
parent: core_base # load configuration from core base.
title: "Training Deberta Reranker"
description:
    Example configuration for training an ettin-150m model with two different losses.

seed: 12 # To mimick the HF xp
nb_repetitions: 3

### Overrides parameters from core_base
learner:
    fabric:
        precision: bf16-mixed

max_doc_len: 1024
normalize_docs_per_batch: true

retrieval:
    requirements: duration=20h & cpu(cores=16) & cuda(mem=30G) * 2
    batch_size: 64
    k: 1000

evaluation:
    all_datasets: false
    in_domain: true
    beir13: true
    robust04: true
    lotte_search: true
    # nanobeir: true


#### Params that are grid searched
grid_search:
    base:
        values_list:
            - microsoft/deberta-v3-base

    learner.loss:
        values_list:
            # - bce
            # - distillRankNET
            # - ADR_MSE
            # - marginMSE
            - hingeLoss
            - infoNCE_RankDistiLLM
            - hingeLoss_RankDistiLLM
            - bce_RankDistiLLM
